name: Maven CI/CD

on:
  push:
    branches: [Development]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio de Git
        uses: actions/checkout@v2

      - name: Configurar JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Probar proyecto con Maven
        run: mvn -B test

      - name: Compilar proyecto con Maven
        run: mvn -B package
